Repository mapbox/mapbox-vision-android-teaser, pull requests merged in 2019-07, with the labels that each got.

#79 Foreground_service permission fix
  app/src/main/java/com/mapbox/vision/examples/activity/main/MainActivity.kt
Labels: Android, Bug, P0

#85 Fix collision bounds calculation
  app/src/main/java/com/mapbox/vision/examples/SafetyModeView.kt
Labels: Android, Bug

#87 Add changelog
  CHANGELOG.md
Labels: Android, P1

#95 Fix route transformation
  app/src/main/java/com/mapbox/vision/examples/activity/ar/ArNavigationActivity.kt
Labels: Bug
