Repository mapbox/mapbox-vision-android-teaser, pull requests merged in 2020-06, with the labels that each got.

#211 [Android] Add reverse landscape orientsation
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/mapbox/vision/teaser/MainActivity.kt
Labels: Android, Enhancement

#213 Disable telemetry for smoke test
  scripts/smoke-test/teaser_smoke_test.py
Labels: Android, Operational excellence

#216 [Android] Draw lane detection with VRE
  app/src/main/kotlin/com/mapbox/vision/teaser/MainActivity.kt
Labels: Android, DO NOT MERGE, Enhancement

#218 Update changelog for 0.13.0
  CHANGELOG.md
Labels: Android, DO NOT MERGE, P0
